django_my_project2/web/main/urls.py
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.main_page, name='home'),
    path('about/', views.about_page, name='about'), 
    path('merch/', views.merch_page, name='merch'), 
    path('contacts/', views.contact_page, name='con'), 
]

django_my_project2/web/music/urls.py
from . import views
from django.urls import path, include

urlpatterns = [
    path('',views.music_page, name='music' ), 
]

django_my_project2/web/users/urls.py
from . import views
from django.urls import path, include

app_name = 'users'

urlpatterns = [
    path('login', views.login , name='login'),
    path('logout/', views.logout , name='logout'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.registration, name='registration')
]

django_my_project2/web/web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('music/', include('music.urls')),
    path('user/', include('users.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_my_project2/web/main/models.py
from django.db import models

django_my_project2/web/music/models.py
from django.db import models

from django.db import models

class Music(models.Model):
    title = models.CharField('Название', max_length=234)
    artist_name = models.TextField('Артитс', blank=True, null=True)
    date = models.DateTimeField('Дата Выхода')    
    image = models.ImageField('Обложка', blank=True, upload_to='images')
    link = models.URLField('Ссылка', blank=True)

    class Meta:
        verbose_name = "Музыка"
        verbose_name_plural = "Музыка"

    def __str__(self):
        return self.title

django_my_project2/web/users/models.py
# users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser): 
    image = models.ImageField(upload_to='user_images', blank=True, null=True)  # Убедитесь, что поле может быть пустым

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

django_my_project2/web/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User

class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите ваше имя пользователя',
        }),
        help_text=None  # Убираем help_text для имени пользователя
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'image']


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'autofocus': True,
            'class': 'form-control',
            'placeholder': 'Введите ваше имя пользователя'
        }),
        help_text=None  # Убираем help_text для имени пользователя
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите ваш пароль'
        }),
        help_text=None  # Убираем help_text для пароля
    )

django_my_project2/web/main/views.py
from django.shortcuts import render

def main_page(request): 
    return render(request, 'main/main_page.html')

def about_page(request): 
    return render(request, 'main/about_page.html')

def merch_page(request): 
    return render(request, 'main/merch_page.html')

def contact_page(request): 
    conn = {
        'send demo tracks to our lable' : 'radiantmusic69@gmail.com',
        'telegram' : '@radiant_lable'
    }
    return render(request, 'main/contact_page.html',{'conn':conn})

django_my_project2/web/music/views.py
from django.shortcuts import render
from .models import Music

def music_page(request): 
    music = Music.objects.order_by('-date')
    return render(request, 'music/music_page.html', {'music' : music})

django_my_project2/web/users/views.py
from django.contrib.auth import authenticate, login as auth_login
from django.shortcuts import render, redirect  
from .forms import UserRegistrationForm, UserLoginForm
from django.contrib import messages

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)  
                return redirect('home')  
            else:
                form.add_error(None, 'Неправильное имя пользователя или пароль.')
    else:
        form = UserLoginForm()
    
    return render(request, 'users/login.html', {'form': form})






def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST, request.FILES)  # Не забудьте request.FILES для загрузки файлов
        if form.is_valid():
            form.save()  # Сохраняем пользователя
            messages.success(request, 'Вы успешно зарегистрировались!')
            return redirect('home')  # Перенаправление на страницу логина
        else:
            messages.error(request, 'Пожалуйста, исправьте ошибки в форме.')
    else:
        form = UserRegistrationForm()
    
    return render(request, 'users/registration.html', {'form': form})
    


    


def logout(request):
    return render(request, 'users/logout.html')
    
    
def profile(request):
    return render(request, 'users/profile.html') 
    
      

django_my_project2/web/main/templates/main/about_page.html
{% extends "base.html" %}
{% load static %}

{% block body %}
    <div class="about-container">
        <h2>О лэйбле RADIANT</h2>
        <img src="{% static 'main/img/radiant copy.png' %}" alt="Лейбл RADIANT" class="about-image">
        <p class="about-text">Лейбл Radiant — это динамично развивающаяся платформа, которая фокусируется на поддержке новых талантов и продвижении их музыки. Мы активно работаем с разнообразными жанрами, от электронной до инди, создавая уникальные коллаборации и поддерживая артистов на каждом этапе их карьеры.</p>
        <p class="about-text">Radiant предлагает гибкие условия дистрибуции. Мы используем передовые технологии для распространения музыки на крупнейших цифровых платформах, таких как Spotify, Apple Music и другие. Благодаря эффективным стратегиям маркетинга и продвижения, мы помогаем артистам достигать широкой аудитории.</p>
        <p class="about-text">Наша команда предоставляет всестороннюю поддержку: от создания качественного контента до разработки индивидуальных маркетинговых стратегий. Мы стремимся создать сообщество, где артисты могут обмениваться идеями и вдохновением.</p>
        <p class="about-text">Если ты артист или музыкальный продюсер, мы будем рады сотрудничеству и помочь реализовать твои творческие идеи!</p>
    </div>
    <header>
        <div class="navbar">
            <div class="navbar-content">
                <a href="{% url 'users:login' %}" class="btn">Войти</a>
                <a href="{% url 'users:registration' %}" class="btn">Зарегистрироваться</a>
            </div>
        </div>
    </header>
    
    
{% endblock %}

django_my_project2/web/main/templates/main/contact_page.html
{% extends "base.html" %}

{% block title %}Contact Page{% endblock %}

{% block body %}
    <div>
        <h4>Contact</h4>
        {% for key, value in conn.items %}
            <h3><strong>{{ key }}: </strong> {{ value }}</h3>
        {% endfor %}
    </div>
{% endblock %}

django_my_project2/web/main/templates/main/main_page.html
{% extends "base.html" %}
{% load static %}

{% block title %}Main Page{% endblock %}

{% block body %}

    <header>
        <div class="navbar">
            <div class="navbar-content">
                <a href="{% url 'users:login' %}" class="btn">Войти</a>
                <a href="{% url 'users:registration' %}" class="btn">Зарегистрироваться</a>
            </div>
        </div>
    </header>
    
    <div class="welcome-container">
        <h4 class="welcome-title">
            Добро пожаловать на лэйбл <a href="{% url 'about' %}" class="radiant">RADIANT</a>
        </h4>
        <p class="welcome-subtitle">АРТИСТ:</p>
        <p class="welcome-subtitle">TOFU</p>
        
        <!-- Картинка, которая только на главной странице -->
        <section id="photo">
            <img src="{% static 'main/img/IMG_9792.jpeg' %}" alt="Image">
        </section>
    </div>
    <img src="{% static 'main/img/radiant copy.png' %}" alt="Лейбл RADIANT" class="about-image">
{% endblock %}

django_my_project2/web/main/templates/main/merch_page.html
{% extends "base.html" %}

{%block title%}Merch Page{%endblock%}


{%block body%}
    <div>
        <h4> Merch </h4>
    

        <header>
            <div class="navbar">
                <div class="navbar-content">
                    <a href="{% url 'users:login' %}" class="btn">Войти</a>
                    <a href="{% url 'users:registration' %}" class="btn">Зарегистрироваться</a>
                </div>
            </div>
        </header>
    </div>
{%endblock%}

django_my_project2/web/music/templates/music/music_page.html
{% extends "base.html" %}
{% load static %}

{% block title %}Music Page{% endblock %}

{% block body %}
    <h4 class="music-title">Music</h4>
    <div class="music-container">
        {% for el in music %}
        <div class="music-item">
            <div class="alert alert-warning">
                {% if el.image %}
                    <img src="{{ el.image.url }}" alt="{{ el.title }}" class="music-cover">
                {% endif %}
                
                <h3>Альбом: {{ el.title }}</h3>
                <p>Артист: {{ el.artist_name }}</p>
                {% comment %} <p>Трек: {{ el.title }}</p> {% endcomment %}
                
                {% if el.link %}
                    <a href="{{ el.link }}" class="btn btn-success">Послушать</a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

django_my_project2/web/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}TOFU{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>

    {% comment %} <header>
        <div class="navbar">
            <div class="navbar-content">
                <a href="{% url 'users:login' %}" class="btn">Войти</a>
                <a href="{% url 'users:registration' %}" class="btn">Зарегистрироваться</a>
            </div>
        </div>
    </header> {% endcomment %}

    <!-- Блок для сообщений -->
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <!-- Кнопка для открытия сайдбара -->
    <button id="toggle-btn">☰</button>

    <!-- Сайдбар -->
    <aside id="sidebar">
        <div id="logo">
            <img src="{% static 'main/img/radiant copy.png' %}" alt="Radiant Logo">
        </div>
        <ul>
            <li><a href="{% url 'home' %}" class="{% if request.path == '/' %}active{% endif %}">
                <i class="fa fa-home"></i> Main Page</a></li>
            <li><a href="{% url 'merch' %}" class="{% if request.path == '/merch/' %}active{% endif %}">
                <i class="fa fa-shopping-cart"></i> Merch</a></li>
            <li><a href="{% url 'con' %}" class="{% if request.path == '/con/' %}active{% endif %}">
                <i class="fa fa-envelope"></i> Contacts</a></li>
            <li><a href="{% url 'about' %}" class="{% if request.path == '/about/' %}active{% endif %}">
                <i class="fa fa-info-circle"></i> About Us</a></li>
            <li><a href="{% url 'music' %}" class="{% if request.path == '/music/' %}active{% endif %}">
                <i class="fa fa-music"></i> New Music</a></li>
        </ul>
    </aside>

    <main>
        <div class="content">
            {% block body %}
            {% endblock %}
        </div>
    </main>
    
    <script src="{% static 'main/js/script.js' %}"></script>
</body>
</html>

django_my_project2/web/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}Вход{% endblock %}

{% block body %}
<div class="login-container">
    <h2>Вход</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}  <!-- Отобразить поля формы -->
        </div>
        <button class="btn-success" type="submit">Войти</button>
    </form>
    <p>Нет аккаунта? <a href="{% url 'users:registration' %}">Зарегистрируйтесь здесь</a>.</p>
    <img src="{% static 'main/img/radiant copy.png' %}" alt="Лейбл RADIANT" class="about-image">
</div>
{% endblock %}

django_my_project2/web/users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

django_my_project2/web/users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block title %}Регистрация{% endblock %}

{% block body %}
<div class="registration-container">
    <h2>Регистрация</h2>
    
    <!-- Проверка наличия ошибок в форме -->
    {% if form.errors %}
        <div class="messages error">
            Пожалуйста, исправьте ошибки в форме.
        </div>
    {% endif %}
    
    <form method="post" enctype="multipart/form-data">  <!-- Для загрузки файлов нужно добавить enctype -->
        {% csrf_token %}
        
        <div class="form-group">
            {{ form.as_p }}
        </div>
        
        <button class="btn-success" type="submit">Зарегистрироваться</button>
    </form>
    <img src="{% static 'main/img/radiant copy.png' %}" alt="Лейбл RADIANT" class="about-image">
</div>
{% endblock %}